using System.ComponentModel.DataAnnotations;
using TallerSaaS.Domain.Enums;

namespace TallerSaaS.Domain.Entities;

public class NominaRegistro
{
    public Guid Id { get; set; } = Guid.NewGuid();
    
    [Required]
    public string UserId { get; set; } = string.Empty;
    
    // We don't link to ApplicationUser here to keep Domain independent of Infrastructure
    // Relations will be configured in DbContext
    
    public Guid TenantId { get; set; }
    public Tenant? Tenant { get; set; }
    
    [Required]
    [MaxLength(7)]
    public string Periodo { get; set; } = string.Empty; // Format: YYYY-MM
    
    public decimal SalarioBase { get; set; }
    public decimal Comisiones { get; set; }
    public decimal Deducciones { get; set; }
    
    // Advanced Plan Empresarial Features
    public decimal IngresosGenerados { get; set; } // Labor revenue generated by the mechanic
    
    public NominaStatus Estado { get; set; }
    
    public DateTime FechaCreacion { get; set; } = DateTime.UtcNow;

    // Computed properties
    public decimal TotalNeto => SalarioBase + Comisiones - Deducciones;
    public decimal TotalCosto => SalarioBase + Comisiones;
    public bool EsRentable => IngresosGenerados >= TotalCosto;
}
